2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:53,336 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:00,211 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:01:08,733 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
2017-04-04 15:00:54,680 ERROR Internal Server Error: /applist/
Traceback (most recent call last):
  File "C:\guanfu\server\python\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
  File "e:\python_project\testdj\testdj\middleware.py", line 32, in __call__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 911, in __init__
  File "C:\guanfu\server\python\lib\logging\__init__.py", line 936, in _open
IOError: [Errno 24] Too many open files: 'e:\\python_project\\testdj\\log\\testdj.log'
